# Generated by Django 4.2.16 on 2024-11-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=200)),
                ("img_url", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.PositiveIntegerField(blank=True, default=0, null=True)),
                (
                    "payment_method",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=4, null=True
                    ),
                ),
                (
                    "customer_type",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                ("categories", models.ManyToManyField(to="recommender.category")),
            ],
        ),
    ]
